# Generated by Django 4.0.4 on 2024-03-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(max_length=12)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('NOM_KAM', models.CharField(max_length=50)),
                ('NOM_DIRECTOR', models.CharField(max_length=50)),
                ('NOM_SUPER', models.CharField(max_length=50)),
                ('SITE', models.CharField(max_length=50)),
                ('ESTADO_ENCUESTA', models.CharField(max_length=50, null=True)),
                ('GENERO', models.CharField(max_length=50, null=True)),
                ('TRAMO_EDAD', models.CharField(max_length=20, null=True)),
                ('P1', models.CharField(max_length=10, null=True)),
                ('P2', models.CharField(max_length=10, null=True)),
                ('P3', models.CharField(max_length=10, null=True)),
                ('P4', models.CharField(max_length=10, null=True)),
                ('P5', models.CharField(max_length=10, null=True)),
                ('P6', models.CharField(max_length=10, null=True)),
                ('P7', models.CharField(max_length=10, null=True)),
                ('P8', models.CharField(max_length=10, null=True)),
                ('P9', models.CharField(max_length=10, null=True)),
                ('P10', models.CharField(max_length=10, null=True)),
                ('P11', models.CharField(max_length=10, null=True)),
                ('P12', models.CharField(max_length=10, null=True)),
                ('P13', models.CharField(max_length=10, null=True)),
                ('P14', models.CharField(max_length=10, null=True)),
                ('P15', models.CharField(max_length=10, null=True)),
                ('P16', models.CharField(max_length=10, null=True)),
                ('P17', models.CharField(max_length=10, null=True)),
                ('P18', models.CharField(max_length=10, null=True)),
                ('P19', models.CharField(max_length=10, null=True)),
                ('P20', models.CharField(max_length=10, null=True)),
                ('P21', models.CharField(max_length=10, null=True)),
                ('P22', models.CharField(max_length=10, null=True)),
                ('P23', models.CharField(max_length=10, null=True)),
                ('P_NPS', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
